CustomerRegistrationMVC/Controllers/BookingController.cs
using CustomerRegistrationMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProductData;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Threading.Tasks;

namespace CustomerRegistrationMVC.Controllers
{
    /*
     * Booking controller for showing and creating bookings
     * 
     * Author James Straka
     */
    public class BookingController : Controller
    {
        // GET: BookingController
        [Authorize]
        public ActionResult Index() // Gets bookings for logged in customer
        {
            int? customer = HttpContext.Session.GetInt32("CurrentCustomer");
            if (customer == null) // There is no customer somehow
                customer = 0;// Show blank data
            var bookings = BookingManager.GetBookingsForCustomer((int)customer);
            decimal totalOwing = 0m;
            foreach(var booking in bookings)
            {
                // If package id exists add price of package to totalOwing
                if(booking.PackageId != null)
                {
                    var package = PackageManager.GetPackageById((int)booking.PackageId);
                    totalOwing += package.PkgBasePrice;
                }
                else
                {
                    totalOwing += 0m;
                }
            }
            // Send total owing to viewbag for display
            ViewBag.Total = totalOwing.ToString("c");
            return View(bookings);
        }

        //// GET: BookingController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // auxilliary method for Create GET
        protected SelectList GetTripTypes()
        {
            // call property types manager to get key/value pairs for property types drop down list 
            var types = TripTypeManager.GetAllAsKeyValuePairs();
            // convert it to a form that drop down list can use, and add to the bag
            var tt = new SelectList(types, "Value", "Text");
            return tt;
        }

        // GET: BookingController/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            try
            {
                BookingAndBookingDetailsModel bookingAndBookingDetailsModel = new BookingAndBookingDetailsModel();
                Package package = PackageManager.GetPackageById(id);
                int? customerId = HttpContext.Session.GetInt32("CurrentCustomer");
                // Customer is somehow null. Should not happen
                if (customerId == null)
                {
                    TempData["IsError"] = true;
                    TempData["Message"] = "Error no customer found. Try again later...";
                    return RedirectToAction("Index", "Home");
                }
                int mostRecentID = BookingManager.GetMostRecentBookingID();
                // Send various information to view
                ViewBag.CustomerID = customerId;
                ViewBag.Package = package;
                ViewBag.BookingID = mostRecentID += 1;
                ViewBag.Price = package.PkgBasePrice.ToString("c");
                ViewBag.TripTypes = GetTripTypes();
                ViewBag.Date = DateTime.Now;
                ViewBag.Description = package.PkgDesc;
                return View(bookingAndBookingDetailsModel);
            }
            catch (DbException ex)
            {
                Console.WriteLine(ex.InnerException.Message);
                TempData["IsError"] = true;
                TempData["Message"] = "Database connection error. Try again later...";
                return RedirectToAction("Index", "Home");
            }
        }

        //POST: BookingController/Create
       [HttpPost]
       [ValidateAntiForgeryToken]
       [Authorize]
        public ActionResult Create(BookingAndBookingDetailsModel bookingAndBookingDetailsModel)
        {
            try
            {
                // Book booking
                BookingAndBookingDetailsModel.Book(bookingAndBookingDetailsModel);
                return RedirectToAction(nameof(Index));
            }
            catch (DbException ex)
            {
                Console.WriteLine(ex.InnerException.Message);
                TempData["IsError"] = true;
                TempData["Message"] = "Database connection error. Try again later...";
                return RedirectToAction("Index" , "Home");
            }
        }

        // GET: BookingController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        // POST: BookingController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: BookingController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: BookingController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

CustomerRegistrationMVC/Controllers/PackageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProductData;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace CustomerRegistrationMVC.Controllers
{
    /*
     * Package controller for displaying package details and packages
     * 
     * Author James Straka, Brett Dawson
     */
    public class PackageController : Controller
    {
        // GET: PackageController
        public ActionResult Index()
        {
            var packages = PackageManager.GetCurrentPackages();
            return View(packages);
        }

        // GET: PackageController/Details/5
        public ActionResult Details(int id, int pageTracker)
        {
            List<Product> ProductList = new List<Product>();
            var package = PackageManager.GetPackageById(id);

            if (package != null) // There is a package with that id
            {
                // Gets all products of package to list and then sends them all to viewbag
                var products = PackagesProductsSupplierManager.GetProductsOfPackage(package.PackageId);
                foreach (var product in products)
                {
                    var productSupplier = ProductSupplierManager.GetProductSupplierWithID(product.ProductSupplierId);
                    ProductList.Add(ProductManager.GetProductWithID((int)productSupplier.ProductId));
                }
                ViewBag.ProductList = ProductList; 
            }
            ViewBag.PageTracker = pageTracker; // Sends page tracker to page for changing items based on what page the user came from
            return View(package);
        }

        // Get list of all packages as key value pairs for select list
        private IEnumerable GetPackagesWithAll()
        {
            var packages = PackageManager.GetPackagesAsKeyValuePairs();
            var list = new SelectList(packages, "Value", "Text").ToList();
            list.Insert(0, new SelectListItem { Value = "0", Text = "All" });
            return list;
        }

        private List<Tuple<decimal, decimal>> PackagePriceRanges()
        {
            var priceRanges = new List<Tuple<decimal, decimal>>
            {
                Tuple.Create(0m, 1000m),
                Tuple.Create(1000m, 2000m),
                Tuple.Create(2000m, 3000m),
                Tuple.Create(3000m, 4000m),
                Tuple.Create(4000m, 5000m)
            };
            // build list of prices that will be used to populate dropdown menu
            return priceRanges;

        }

       
        public ActionResult PackagesSortingByPrice(decimal min = 0, decimal max = 0)
        {
            try
            {
                ViewBag.Packages = GetPackagesWithAll();
                ViewBag.PriceRanges = PackageManager.GetPackagesByPriceRange(min,max);
                return View("PackagesSortingByPrice");
            }
            catch (Exception)
            {
                TempData["Message"] = "Database connection problem. Try again later.";
                TempData["IsError"] = true;
                return RedirectToAction("_Index");
            }
        }

        public ActionResult PackagesByPrice(decimal min, decimal max)
        {
            return ViewComponent("PackagesSorting", new { min, max});
        }

        //public ActionResult PackagesSortingByPrice()
        //{
        //    Tuple<List<decimal>, List<Package>> tuple;
        //    tuple = new Tuple<List<decimal,decimal>, List<Package>(PackageManager.PackagePriceRanges(), PackageManager.GetCurrentPackages());
                
        //      return View("PackagesSortingByPrice", tuple);
        //}

        //// GET: PackageController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: PackageController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: PackageController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: PackageController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: PackageController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: PackageController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: PackageController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

CustomerRegistrationMVC/ViewComponent/PackagesSortingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProductData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/*
 * Packages sorting view component
 * 
 * Author Brett Dawson, James Straka
 */
namespace CustomerRegistrationMVC.ViewComponents
{
    public class PackagesSortingViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(decimal min, decimal max)/*, int sortType*/
        {
            List<Package> packages;

            //if (sortType == 0) // User is sorting by decimal
            //{
                if(min == 0 && max == 0)
                {
                    // Get all travel packages
                    packages = PackageManager.GetAllPackages();
                }
                else
                {
                    // Get travel packages within range
                    packages = PackageManager.GetPackagesByPriceRange(min, max);
                } 
            //}
            //if (sortType == 1) // Brett - I modified this so that the user can sort by start date. 
            //{
            //    DateTime startDate = DateTime.Now;
            //    packages = PackageManager.GetPackagesByStartDate(startDate);
            //}

            return View(packages);
        }
    }
}

CustomerRegistrationMVC/Views/Package/Details.cshtml
@model ProductData.Package

@{
    ViewData["Title"] = "Details";
}
<br />
<br />
<section class="jumbotron text-center">
    <h1>
        <b> Package Details</b>
    </h1>
</section>
    <div class="jumbotron-package">
        <dl>
            <dt class="row">
                Package ID:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PackageId)
            </dd>
            <dt class="row">
                @Html.DisplayNameFor(model => model.PkgName):
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PkgName)
            </dd>
            <dt class="row">
                @Html.DisplayNameFor(model => model.PkgStartDate):
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PkgStartDate)
            </dd>
            <dt class="row">
                @Html.DisplayNameFor(model => model.PkgEndDate):
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PkgEndDate)
            </dd>
            <dt class="row">
                Description:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PkgDesc)
            </dd>
            <dt class="row">
                @Html.DisplayNameFor(model => model.PkgBasePrice):
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PkgBasePrice)
            </dd>
            @*<dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.PkgAgencyCommission)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.PkgAgencyCommission)
                </dd>*@
        </dl>
        @if (ViewBag.ProductList != null)
        {
            <h4><u>Products Included In Package</u></h4>
            @foreach (var prod in ViewBag.ProductList)
            {
                <h6>@prod.ProdName</h6>
            }
        }
</div>
<div class="center-package">
    @if (ViewBag.PageTracker == 1)
    {
        <input class="button1" type="button" value="Back" onclick="location.href='@Url.Action("Index","Booking")'" />
    }
    else if (ViewBag.PageTracker == 0)
    {
        <input class="button1" type="button" value="Back" onclick="location.href='@Url.Action("Index","Package")'" />
    }
</div>

CustomerRegistrationMVC/Views/Package/Index.cshtml
@model IEnumerable<ProductData.Package>

@{
    ViewData["Title"] = "Packages";
}
<br />
<br />
<section class="jumbotron">
    <div class="text-center">
        <h1 class="jumbotron-current display-1">
            <b>Currently Available Packages</b>
        </h1>
        <h4 class="jumbotron-subtitle">
        </h4>
    </div>
</section>
<table class="d-block table-package" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PackageId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PkgName)
            </th>
            @*<th>
            @Html.DisplayNameFor(model => model.PkgStartDate)
        </th>*@
            <th>
                @Html.DisplayNameFor(model => model.PkgEndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PkgDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PkgBasePrice)
            </th>
            <th>
                Detail
            </th>
            <th>
                Book
            </th>
            @*<th>
            @Html.DisplayNameFor(model => model.PkgAgencyCommission)
        </th>*@

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PackageId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PkgName)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.PkgStartDate)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.PkgEndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PkgDesc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PkgBasePrice)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.PkgAgencyCommission)
                    </td>*@
            <td>
                <input class="button-pkg" type="button" value="Details" onclick="location.href='@Url.Action("Details","Package", new { id = item.PackageId })'" />

            </td>
            <td>
                <input class="button-pkg" type="button" value="Book Now!" onclick="location.href='@Url.Action("Create","Booking", new { id = item.PackageId, pageTracker = 1})'" />
            </td>
            </tr>
        }
    </tbody>
</table>

CustomerRegistrationMVC/Views/Package/PackagesSortingByPrice.cshtml
@{ ViewData["Title"] = "Filter by price";}

<h1>Packages filtered by price</h1>

<div class="form-group">
    <select id="uxPackages" asp-items="@ViewBag.PriceRanges" class="form-control">
    </select>
</div>

<div id="uxDisplay">
    @await Component.InvokeAsync("PackagesSorting", (0,0))
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
        // .change function waits for a change in the uxPackages price range
            $("#uxPackages").change(function () {
                var minPrice = $("#uxPackages").val();
                var maxPrice = $("#uxPackages").val();
                // call asynchronous javascript function .ajax
                $.ajax({
                    method: 'GET',
                    url: '/Package/PackagesByPrice',
                    data: { minPrice, maxPrice  }
                }).done(function (result, statusText, xhdr) {
                    $("#uxDisplay").html(result);
                    });
            });
        });
    </script>
    }